spring.application.name=petadoption
# Conexión a MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://jfernand3z24_db_user:OFYxFci7AlGp21By@cluster0.iz9oxuk.mongodb.net/petadoption_db?retryWrites=true&w=majority&appName=Cluster0

# Configuración de Thymeleaf
spring.thymeleaf.cache=false

# Logs
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
